### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by IlGian98** [IlGianFarm/birthdays#10]
Comment the code, create README and LICENSE.

**Comment by alemusca** [comment]
comment sign_up and log_in in 22ee211e5220e3244677d741f188c07c9776c459

**Comment by alemusca** [comment]
comment argsmain, birthdays.py and csv_reader in 4173cab555a6b78cce45ad8a48bd53a66531f831

**Comment by alemusca** [comment]
comment main.py in 69685fc1c737efd2855861adf4e44df8ad2ac757

**Comment by alemusca** [comment]
create README (to be updated) in 5a349355e6c129473e476ed9f25d9ac2cd381dc9

**Comment by alemusca** [comment]
Updated package README and removed LICENSE in dc896ce9abcc76c9e8b5f0af9057cb36e1c560ca

**Comment by LucaBrigo** [comment]
changed package name and all files where it was mentioned in 5bcb0dc57790f2065dda76fe524175d7d2e520c9

**Comment by LucaBrigo** [comment]
updated package name in test_main.py in 1f39a3da39b76744784daa9692b674d0f96e5dad

**Comment by IlGian98** [comment]
Mistakes were made. We attempted to change the name of the directory of our package as we realized it contained uppercase letters, however we were not successful. We realize we made a mistake and we apologize.
All in a420e6b2f186d7dd9d516fedce854783d6f23431
