### ISSUE TITLE
Post Evaluation Corrections

### ISSUE THREAD

**Issue by alemusca** [IlGianFarm/birthdays#13]
For info check evaluation document on whatsapp

**Comment by LucaBrigo** [comment]
Changed the package name from python_package to pypackage in 8756c04632073d625ec9ec913cad9cbac59b6f51

**Comment by alemusca** [comment]
Renamed imports and made tests successful in edfd07d7c210b6f8da9872b67b54b4fc6be70b92

**Comment by LucaBrigo** [comment]
Added Doc Strings e28bb62f0d6eeca6acd1d48d601608666a17e865

**Comment by IlGian98** [comment]
fixed pep8 on some files, updated README and created documentation in 128b2e81131101e2ff2e8b7a2dc7e457d6fccf11

**Comment by LucaBrigo** [comment]
Updated README c6c450e7a4666fd9c71e667aa208b973c780b77a

**Comment by IlGian98** [comment]
updated argsmain and README in 2b3ac20e5f12445f6d22178ac676186bd858e346
