### ISSUE TITLE
Enable User Input

### ISSUE THREAD

**Issue by IlGian98** [IlGianFarm/birthdays#5]
For instructions look at Homework W2 task 3.

**Comment by LucaBrigo** [comment]
Created sysargv file and added import sys.
7820f7898a0ed24d18e48c640b512a9176bb6dcf

**Comment by LucaBrigo** [comment]
Updated more in 
55663e0c2a882278429a2a35e7503f0fca5b702c

**Comment by IlGian98** [comment]
removed sysargv (as user input enabled through argparse) in 025481d17185933c35dab1d123bd02185ae8eec6
