### ISSUE TITLE
Implement “argparse”

### ISSUE THREAD

**Issue by IlGian98** [IlGianFarm/birthdays#6]
For instructions look at task 1 in Homework W3.

**Comment by alemusca** [comment]
Changed main.py 3e5ed7e296db8955e0377fd57d26392bdb402ad7

**Comment by alemusca** [comment]
Added more in 95e916bb61978604032ab0ebe8643abaf812e8db

**Comment by IlGian98** [comment]
Update argparse and added birthdays in 796644cca00906e7815a3b7bc53baba2a12eafc2
All fit pep8.
