### ISSUE TITLE
Use the CSV module

### ISSUE THREAD

**Issue by IlGian98** [IlGianFarm/birthdays#7]
For instructions look at task 2 in Homework W3.

**Comment by LucaBrigo** [comment]
Create csv file in 3f557b438b7b708151edd5703b275b5d526ddf9c

**Comment by LucaBrigo** [comment]
Created reader in 6953c12e353ce7694ca93d3fb3198ced375c7ebd

**Comment by IlGian98** [comment]
Updated csv, reader and main in b876c5e9e4f6139921024aa6ecf36a32cb189444

**Comment by LucaBrigo** [comment]
Moved csv_reader and csv into Package in bb45992cdfaac7803810a6cf06265b3c45a6b529

**Comment by LucaBrigo** [comment]
Update Reader in 7db74ab9523e8dc738d4060d5b22c8bb0f4f91af

**Comment by IlGian98** [comment]
updated reader to fit pep8 inb479c8fdcaa29404b053c8ff57e6c3585908c7db

**Comment by IlGian98** [comment]
updated reader to fit pep8 in b479c8fdcaa29404b053c8ff57e6c3585908c7db
